config/routes.rb
Rails.application.routes.draw do
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  concern :paginatable do
    get '(page/:page)', action: :index, on: :collection, as: ''
  end

  resources :people, concerns: :paginatable
  resources :sessions, only: [:new, :create, :destroy]
  resources :subscribers, only: [:create, :destroy] do
    get :notify, on: :member
  end
  get 'settings', to: 'settings#index', as: 'settings'

  root 'people#index'

end

app/models/person.rb
class Person < ActiveRecord::Base
  mount_uploader :avatar, AvatarUploader
  mount_base64_uploader :avatar, AvatarUploader

  validates :name,
            presence: true,
            length: {in: 2..20},
            format: {with: /\A[А-Яа-яёЁ]+\z/}

  validates :lastname,
            presence: true,
            length: {in: 2..20},
            format: {with: /\A[А-Яа-яёЁ]+\z/}

  validates :email,
            format: {with: /.+@.+\..+/i},
            allow_blank: true

  validates :phone,
            length: {is: 3},
            numericality: {only_integer: true, allow_nil: true},
            allow_blank: true

  validates :birthday_sort,
            presence: true, unless: 'birthday.nil?'


  before_validation :complete_email
  before_validation :downcase_email
  before_validation :capitalize_name
  before_validation :fill_birthday_sort


  scope :birthday, -> do
    from = Date.today.strftime('%m%d')
    to = 15.days.from_now.strftime('%m%d')
    if from > to # begin of the year
      where('(birthday_sort >= ? AND birthday_sort <= ?) OR (birthday_sort >= ? AND birthday_sort <= ?)', from, '1231', '0101', to).order(:birthday_sort)
    else
      where(birthday_sort: from..to).order(:birthday_sort)
    end
  end


  def self.birthday_order
    now = Time.now.strftime("%m%d").to_i

    all.sort_by do |person|
      if person.birthday_sort.to_i < now
        (person.birthday_sort.nil?) ? 2500 : person.birthday_sort.to_i + 1231
      else
        person.birthday_sort
      end
    end
  end


  def full_name
    [lastname, name].join(' ')
  end

  def print_coming_age
    age = (Date.current - self.birthday).to_i / 365

    years_old = case age.to_s.last.to_i
    when 1
      'год'
    when 2..4
      'года'
    else
      'лет'
    end

    "#{age} #{years_old}"
  end

  private

  def complete_email
    unless self.email.blank?
      self.email << '@svarbi.ru' unless self.email.include? '@'
    end
  end

  def downcase_email
    self.email.downcase! unless self.email.blank?
  end

  def capitalize_name
    self.name = self.name.mb_chars.capitalize unless self.name.blank?
    self.lastname = self.lastname.mb_chars.capitalize unless self.lastname.blank?
  end

  def fill_birthday_sort
    self.birthday_sort = self.birthday.strftime("%m%d") unless self.birthday.nil?
  end

  def self.by_letter(letter)
    where('lastname LIKE ?', "#{letter}%")
  end
end

app/models/russian_date.rb
class RussianDate
  Months = {
      января: '01',
      февраля: '02',
      марта: '03',
      апреля: '04',
      мая: '05',
      июня: '06',
      июля: '07',
      августа: '08',
      сентября: '09',
      октября: '10',
      ноября: '11',
      декабря: '12',
  }

  def self.rus_to_date(rus)
    date = replace_month(rus)
    Date.parse(date) if date
  end

  def self.date_to_rus(date, short = false)
    return date if date.nil?
    ar = date.to_formatted_s(:iso8601).split('-')
    month = Months.key(ar[1]).to_s

    short ? "#{ar[2]} #{month}" : "#{ar[2]} #{month} #{ar[0]}"
  end


  private

  def self.replace_month(rus)
    ar = rus ? rus.split : nil
    if ar && ar[1]
      month = ar[1].to_sym
      return ar[2] + Months[month] + ar[0] if Months[month]
    end

    nil
  end
end

app/models/subscriber.rb
class Subscriber < ActiveRecord::Base
  validates :email, presence: true
  validates :email, format: {with: /.+@.+\..+/i}
  validates :email, uniqueness: true


  def self.notify_all
    all.each do |subscriber|
      subscriber.notify
    end
  end

  def notify
    BirthdayMailer.notify(self).deliver_now
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates :login, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  after_action :verify_authorized, except: [:index, :show]


  private

  def authenticate
    current_user.nil?
  end

  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user


  def user_not_authorized
    flash[:alert] = 'У вас нет прав на данное действие'
    redirect_to login_path
    # redirect_to(request.referrer || root_path)
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :authenticate, except: [:index, :show]
  before_action :load_person, only: [:show, :edit, :update, :destroy]
  before_action :convert_birthday, only: [:create, :update]

  def index
    if params[:letter]
      @people = Person.by_letter(params[:letter]).order(:lastname).page(params[:page])
    else
      @people = Kaminari.paginate_array(Person.all.birthday_order)
                        .page(params[:page]).per(20)
    end
  end

  def show
  end

  def new
    @person = Person.new
    authorize @person
  end

  def create
    @person = Person.new(person_params)
    authorize @person

    if @person.save
      redirect_to people_path
      flash[:notice] = 'Сотрудник успешно создан!'
    else
      render :new
    end
  end

  def edit
    @person.birthday = RussianDate::date_to_rus(@person.birthday)
    @person.email = @person.email.sub('@svarbi.ru', '')
  end

  def update
    if @person.update(person_params)
      redirect_to people_path
    else
      render :edit
    end
  end

  def destroy
    if @person.destroy
      redirect_to people_path
      flash[:notice] = 'Сотрудник успешно удалён!'
    end
  end


  private

  def load_person
    @person = Person.find(params[:id])
    authorize @person
  end

  def person_params
    params.require(:person).permit(:name, :lastname, :email, :phone, :birthday, :avatar)
  end

  def convert_birthday
    params[:person][:birthday] = RussianDate.rus_to_date(params[:person][:birthday])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_after_action :verify_authorized

  def new
  end

  def create
    user = User.find_by_login(params[:login])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: 'Вход успешно выполнен'
    else
      flash.now.alert = 'Неправильный логин/пароль'
      render :new
    end
  end

  def destroy
    # session[:user_id] = nil
    session.delete(:user_id)
    redirect_to root_path, notice: 'Выход выполнен успешно'
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController

  def index
    @subscriber = Subscriber.new
    @subscribers = Subscriber.all

    authorize :setting, :index?
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  before_action :load_subscriber, only: [:destroy, :notify]

  def create
    @subscriber = Subscriber.new(subscriber_params)
    authorize @subscriber

    @subscriber.save
  end

  def destroy
    authorize @subscriber
    @subscriber.destroy
  end

  def notify
    authorize @subscriber
    @subscriber.notify
  end


  private

  def load_subscriber
    @subscriber = Subscriber.find(params[:id])
  end

  def subscriber_params
    params.require(:subscriber).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title !СВАРБИ!
    = stylesheet_link_tag 'application'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  body
    .navbar.navbar-default.navbar-fixed-top role='navigation'
      .container
        .navbar-header
          button.navbar-toggle data-target='.navbar-collapse' data-toggle='collapse' type='button'
            span.sr-only Toggle navigation
            span.icon-bar
            span.icon-bar
            span.icon-bar
          = link_to 'СВАРБИ', root_path, class: 'navbar-brand'
        .navbar-collapse.collapse
          ul.nav.navbar-nav
            li
              = link_to 'Сотрудники', people_path
            - if policy(:setting).index?
              li
                = link_to 'Настройки', settings_path
          ul.nav.navbar-nav.navbar-right
            - if current_user
              li
                = link_to 'Выход', logout_path
            - else
              li
                = link_to 'Вход', login_path

    .container
      = yield :letters

      - flash.each do |name, msg|
        div class="alert alert-#{name == 'notice' ? 'success' : 'danger'}"
          button.close type='button' data-dismiss='alert' aria-hidden='true' &times;
          = msg

      = yield

app/views/people/_form.html.slim
br
= form_for @person do |f|

  - if @person.errors.any?
    br
    #error_explanation
      h4 Сотрудник не сохранён!
      ul
        - @person.errors.values.each do |error|
          li = error.first
    br

  .row
    .col-xs-12.col-sm-8.col-sm-push-4
      #upload-demo
        button.upload-result Сохранить

    .col-xs-12.col-sm-4.col-sm-pull-8
      = label_tag 'Аватар'
      input#upload type='file' value='Выберите файл'
      #example
        - if @person.avatar?
          = image_tag @person.avatar_url
          = image_tag @person.avatar_url :small
      br

      .form-inputs

        .form-group
          = f.label :name
          = f.text_field :name, class: 'form-control'

        .form-group
          = f.label :lastname
          = f.text_field :lastname, class: 'form-control'

        .form-group.email
          = f.label :email
          .input-group
            = f.text_field :email, class: 'form-control'
            span.input-group-addon @svarbi.ru


        .form-group
          = f.label :phone
          = f.text_field :phone, class: 'form-control'

        .form-group
          = f.label :birthday
          br
          .col-sm-6
            = f.text_field :birthday, class: 'datetimepicker9 form-control'

    = f.hidden_field :avatar

  br
  br

  .form-actions
    = f.submit nil, class: 'btn btn-primary'
br

.row
  .col-md-2.col-md-offset-5
    = link_to 'К списку сотрудников', people_path, class: 'btn btn-primary'

script Crop.init();

app/views/people/edit.html.slim
h1 Редактирование сотрудника

= render 'form'

app/views/people/index.html.slim
- content_for :letters
  .btn-group.btn-group-justified
    - ('А'..'Я').each do |letter|
      - next if ['Ъ', 'Ь'].include?(letter)
      = link_to letter, people_path(letter: letter), class: 'btn btn-default'
    = link_to '*', people_path, class: 'btn btn-default'
  br


h1 Сотрудники

table.table.table-striped.table-hover.table_people
  thead
    tr
      th
      th Имя
      th Email
      th Телефон
      th День рождения
      th
  tbody
    - @people.each do |person|
      tr
        td.avatar
          = link_to person do
            = image_tag person.avatar_url(:small) if person.avatar?
        td = link_to person.full_name, person_path(person)
        td = person.email
        td = person.phone
        td = RussianDate::date_to_rus(person.birthday)
        td style="text-align: right"
          - if current_user
            = link_to 'редактировать', edit_person_path(person), class: 'btn btn-default btn-xs'
            = ' '
            = link_to 'уволить', person_path(person), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Точно уволить?' }

= paginate @people

- if current_user
  .form-actions
    = link_to 'Новый сотрудник', new_person_path, class: 'btn btn-primary'

br
br

app/views/people/new.html.slim
h1 Новый сотрудник

= render 'form'

app/views/people/show.html.slim
h3 = @person.full_name

- if @person.avatar?
  = image_tag @person.avatar_url
  br

br

.panel.panel-default
  .panel-heading Личное дело
  table.table.person_detail
    tr
      th.param Email
      td = link_to @person.email, "mailto:#{@person.email}"
    tr
      th Телефон
      td = @person.phone
    tr
      th День рождения
      td = @person.birthday

- if current_user
  .form-actions
    = link_to 'Редактировать', edit_person_path(@person), class: 'btn btn-primary'

br

.row
  div class='col-md-2 col-md-offset-5'
    = link_to 'К списку сотрудников', people_path, class: 'btn btn-primary'

app/views/persons/index.html.slim
h1 Сотрудники

table class="table table-stiped table-hover"
  thead
    tr
      th Имя
      th Email
      th Телефон
      th День рождения
      th
  tbody
    - @persons.each do |person|
      tr
        td
          = link_to "#{person.name} #{person.lastname}", '#'
        td = person.email
        td = person.phone
        td = person.birthday
        td style="text-align: right"
          = link_to 'Edit', '#', class: 'btn btn-default btn-xs'
          = ' '
          = link_to 'Destroy', '#', class: 'btn btn-xs btn-danger'

.form-actions
  = link_to 'Новый сотрудник', '#', class: 'btn btn-primary'
      
      
/ <h1>Contacts</h1>


/ <table class="table table-striped table-hover">
/   <thead>
/     <tr>
/       <th>Name</th>
/       <th>Email</th>
/         <th></th>
/     </tr>
/   </thead>
/ 
/   <tbody>
/     <% @persons.each do |person| %>
/       <tr>
/         <td><a href="/contacts/2"><%= person.name %> <%= person.lastname %></a></td>
/         <td><%= person.email %></td>
/           <td style="text-align:right;">
/             <a href="/contacts/2/edit" class="btn btn-default btn-xs">Edit</a>
/             <a rel="nofollow" href="/contacts/2" data-method="delete" data-confirm="Are you sure?" class="btn btn-xs btn-danger">Destroy</a>
/           </td>
/       </tr>
/     <% end %>
/   </tbody>
/ </table>
/ 
/ <div class="form-actions">
/   <a href="/contacts/new" class="btn btn-primary">New Contact</a>
/ </div>

app/views/settings/index.html.slim
h1 Настройки

br

h5 Подписчики на рассылку уведомлений о ДР
hr

= form_for @subscriber, remote: true do |f|
  .panel.panel-default
    .panel-heading Список email
    table.table
      - @subscribers.each do |subscriber|
        tr id="subscriber-id-#{subscriber.id}"
          td = subscriber.email
          td.action
            = link_to '', subscriber_path(subscriber), method: :delete, remote: true, class: 'glyphicon glyphicon-remove', title: 'удалить'
            = link_to '', notify_subscriber_path(subscriber), remote: true, class: 'glyphicon glyphicon-send', title: 'отправить письмо'

  .input-group
    = text_field_tag 'subscriber[email]', nil, placeholder: 'email', class: 'form-control'
    span.input-group-btn
      button.btn.btn-default type='button' добавить
  #subscriber_errors

app/views/subscribers/create.js.erb
<% if @subscriber.errors.any? %>
  $('#subscriber_errors').html('<%= @subscriber.errors.messages[:email][0] %>');
<% else %>
  $('#new_subscriber table').append('<tr id="subscriber-id-<%= @subscriber.id %>"><td><%= @subscriber.email %></td><td class="action"><a href="/subscribers/<%= @subscriber.id %>" data-method="delete" rel="nofollow" data-remote="true" title="удалить" class="glyphicon glyphicon-remove"></a><a href="/subscribers/<%= @subscriber.id %>/notify" data-remote="true" rel="nofollow" title="отправить письмо" class="glyphicon glyphicon-send"></a></td></tr>');
  $('#subscriber_email').val('');
<% end %>

app/views/subscribers/destroy.js.erb
$('#subscriber-id-<%= @subscriber.id %>').remove();